Update make-all-test.yml

diff --git a/.github/workflows/make-all-test.yml b/.github/workflows/make-all-test.yml
--- a/.github/workflows/make-all-test.yml
+++ b/.github/workflows/make-all-test.yml
@@ -17,5 +17,9 @@ jobs:
       run: |
         make all-test
         docker-compose -f test-docker-compose.yaml up -d
-        docker compose -f test-docker-compose.yaml up cypress
-        
+        docker-compose -f test-docker-compose.yaml run --rm cypress
+        exit_code=$?
+        if [ $exit_code -ne 0 ]; then
+          echo "Cypress tests failed with exit code $exit_code"
+          exit $exit_code
+        fi
